src/Foundation/Serialization/code/App_Config/Include/Foundation/Foundation.Serialization.config
3.1 has improved config grammar to exclude children that is less implicit than a trailing slash and more obvious to a reader what the intention is.
This PR switches to using that.
=> Utilize Unicorn 3.1 explicit exclude children grammar for clarity

Habitat.sln, src/Feature/PageContent/code/Views/PageContent/PageTitle.cshtml, src/Foundation/SitecoreExtensions/Tests/Renderings/QueryableDatasourceRenderingModelTests.cs, src/Foundation/SitecoreExtensions/code/Rendering/QueryableDatasourceRenderingModel.cs, src/Project/Habitat/serialization/Habitat.Website.Templates/Habitat/Page Types/Employees folder/__Standard Values.yml
Fixed the QueryableDatasourceRenderingModel to default to search under the current items and a default of max 10 items
Cleanup: Moved WebEssentials file to Configuration folder
Changed header lead to div to cater for p tags from the RTE
=> Review fixes

src/Feature/faq/code/Sitecore.Feature.FAQ.csproj
**02-Publish-All-Projects** task reports issues during build of FAQ feature project:
```
[12:19:28] Building project: src\Feature\faq\code\Sitecore.Feature.FAQ.csproj
[12:19:28] Using automatic maxcpucount
[12:19:28] Building project: 1 item
[12:19:29] { [Error: Command failed: ] killed: false, code: 1, signal: null }
[12:19:29] Build failed!
[12:19:29] Finished 'Publish-Feature-Projects' after 1.22 s
[12:19:29] Starting 'Publish-Project-Projects'...
```
MS Build Error message
```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.Web.Publishing.targets(2998,5): error
\Feature.FAQ.Serialization.config failed. Could not find a part of the path 'App_Config\include\FAQ\Feature.FAQ
```
Fixed include line according to file system structure.
=> Fixed incorrect include

applytransform.targets, gulpfile.js
Now there can be more than one transformation in each project and process takes much less time
Previous solution was causing an error if there was more than one transformation in any project.
Also since transformation process is only triggered if there is transformation file, it takes much less time than running it for each project regardless.
=> ApplyTransform tweak to handle multiple transforms with in project

src/Feature/faq/code/Sitecore.Feature.FAQ.csproj
Don't know why, but the platform target for the FAQ proj has been set to x64 CPU
=> Make FAQ csproj for anyCPU, like all others

src/Foundation/Testing/code/Sitecore.Foundation.Testing.csproj
Having Web.config marked as content causes this file to overwrite the Website\web.config, breaking the site.
=> Correct project setting for Web.config

src/Foundation/Assets/code/App_Config/Include/Foundation/Foundation.Assets.config, src/Foundation/Assets/code/Models/Asset.cs, src/Foundation/Assets/code/Pipelines/GetPageRendering/AddAssets.cs, src/Foundation/Assets/code/Repositories/AssetRepository.cs, src/Foundation/Assets/code/Services/RenderAssetsService.cs, src/Foundation/Theming/code/App_Config/Include/Foundation/Foundation.Theming.Serialization.config, src/Foundation/Theming/code/App_Config/Include/Foundation/Foundation.Theming.config
Makes it possible to specify sites (or site wildcards) on the assets in the config so that css/scripts are only loaded on the pages of the specified site.
=> Site Specific Assets

src/Feature/Accounts/code/Services/UserProfileProvider.cs
Fix for Bug 38423: In Habitat Include Base Templates, because _LegalProfile Template now inherits from _UserProfile (Partt 2 of the fix in Sitecore.Demo)
=> Bug38423 Fix -> Include Base Templates

src/Foundation/Indexing/code/Repositories/IndexingProviderRepository.cs
Fixed stack overflow exception issue (worker process crash) when there are no providers that implement ISearchResultFormatter.
Note: Thread Safety issues are still to be addressed.
=> Fixed stack overflow exception issue (worker process crash)

src/Foundation/Assets/code/Pipelines/GetPageRendering/AddAssets.cs, src/Foundation/Assets/code/Repositories/AssetRepository.cs
Should solve #203.
Making the AssetRepository ThreadStatic prevents locking so should improve performance slightly.
=> Updated Asset Repository to not keep assets between pages

gulp-config.js, gulpfile.js
A number of colleagues were getting errors with the msbuild command in Task Runner. We tracked it down to an issue where some computers have a Windows Environment variable set that will be used for the Platform property of MsBuild when the parameter is not defined. This caused the command to fail. This pull request adds the option of setting the Platform parameter, defaulting it to 'AnyCpu', which will avoid this issue for all Windows machines. See this related thread: https://social.msdn.microsoft.com/Forums/vstudio/en-US/2253d930-fe68-4ff0-a8f2-19bfbb9a0cbb/msbuild-platformbpc?forum=msbuild.
=> Gulp MsBuild Error Patch

gulpfile.js
Fixes an issue where only a subset of the existing Views folders will be watched for changes because the result of gulp.src() was not returned
=> Add return on gulp.src() in Auto-Publish-Views task

src/Foundation/SitecoreExtensions/code/Extensions/ItemExtensions.cs
This change was in response to some seemingly random errors we were getting when on a project when trying to use the LinkFieldUrl() function. It was occasionally throwing errors complaining about a missing "url" parameter. This seemed to be because older, XML based link generation functions were being used. This commit updates this function to be more robust and properly handle additional linkfield options (media, javascript, etc...) as well.
=> Updating ItemExtensions.cs to better handle Linkfields

src/Foundation/SitecoreExtensions/code/Properties/AssemblyInfo.cs
This Foundation layer module appears to incorrectly refer to itself as a Feature layer module. This corrects the information to match the title.
=> Fix product name of Foundation.SitecoreExtensions

build/assets/readme.txt, install-xp0.ps1, uninstall-xp0.ps1
When only the JRE (and not the JDK) is installed, the dependency validation fails. This fixes that.
Additional fixes have also been made to improve reliability and reduce errors, especially around Solr, based on setting Habitat up on a fresh computer that just had Solr + IIS. See commits for details.
=> Fix dependency validation issue when only JRE (and not JDK) is installed

src/Foundation/SitecoreExtensions/code/Extensions/SiteExtensions.cs
Removed the dependency on the static Sitecore Context. It may trigger weird behavior when working with multiple sites since the site passed to the extension may not be the Context.Site.
=> Remove dependency on static context in site extensions

src/Feature/Maps/code/packages.config, src/Foundation/SitecoreExtensions/code/packages.config
There are issues doing a Nuget-Restore from the gulp command line because two modules have references to assemblies that aren't included in the nuget package references. This adds the two references that are missing and makes command line gulp processes work as expected without opening the IDE to fix them.
Questions/Concerns: dco@sitecore.net
=> Added missing dependencies in the packages.config for two modules.

README.md, docs/01-Getting-Started.md, docs/02-Resources.md, docs/03-Licensing.md, docs/04-Contribute.md, docs/index.md, install-xp0.ps1, settings.ps1, uninstall-xp0.ps1
First pass on docs for 9.0.1:
* Added Version list to top of 01
* Minor fixes for broken links
* Added clarifying language around Habitat being an example, not requirements or a starter kit
* Added Contributors since last update
Fix for #390 
* Moved membership for the app pool to after the installation, in case a prior error out
* Uses $SitecoreSiteName
* Moved to try-catch format due to errors stemming from the if check
* Removes membership in Uninstall script
Removed redundant variable definitions from Settings.ps1
=> Feature/901docs and #390 fix

install-xp0.ps1
Adding '-Repository $AssetPSRepositoryName' to the SitecoreInstallFramework installation call to ensure a specific repository is used.
Issue would only come up with Sitecore employees who have access to multiple repositories that host SitecoreInstallFramework but it's not a bad idea to have the Repository specified since it's already captured in the settings.ps1 file.
=> Adding '-Repository $AssetPSRepositoryName' to install.ps1

gulpfile.js
Fixes bug causing gulp.watch() to monitor only the first 16 bin folders found in the solution
=> Add missing 'return' keyword

src/Project/Common/code/Directory.Build.props, src/Project/Common/code/Web.config.xdt, src/Project/Habitat/code/Sitecore.Habitat.Website.csproj
* Ensure we don't replace the version shipped with the product
* Add explicit reference to 4.5.0 in Project layer
* Ensure project dependencies are such that it's deployed last
=> [closes #476] Change approach to fixing System.Buffers reference issue
