Sitecore/Habitat

src/Feature/Navigation/code/Controllers/NavigationController.cs, src/Feature/Navigation/code/Sitecore.Feature.Navigation.csproj, src/Feature/Person/code/Templates.cs, src/Feature/Person/code/Views/Person/Quote.cshtml, src/Feature/Person/serialization/Feature.Person.Templates/Person/_Quote/Details/Cite Origin.yml, src/Project/Habitat/serialization/Habitat.Website.Content/Habitat/Home.yml
Change Company to CiteOrigin to accommodate other use cases
Added no data source alert to LinkMenu
=> Minor fixes

src/Feature/Demo/tests/Controllers/DemoControllerTests.cs, src/Feature/Demo/tests/DemoContentItem.cs, src/Feature/Demo/tests/Sitecore.Feature.Demo.Tests.csproj
- Minimized tests size
- Introduced [SUT](http://xunitpatterns.com/SUT.html) using [AutoFixture]
- Removed some redundant `ITracker`'s
=> Simplify unit tests applying AutoFixture

src/Foundation/Multisite/code/Commands/CreateRenderingSettings.cs, src/Foundation/Multisite/serialization/Foundation.Multisite.Branches/MultiSite/RenderingSettings.yml
=> Wrong location for rendering settings

src/Foundation/Multisite/code/Commands/CreateRenderingSettings.cs, src/Foundation/Multisite/serialization/Foundation.Multisite.Branches/MultiSite/RenderingSettings.yml
=> Revert "Wrong location for rendering settings"

src/Foundation/Multisite/code/Commands/CreateRenderingSettings.cs
Fixed problem with empty parameter while using chunk insert action
=> #137 | Wrong location for rendering settings

src/Foundation/SitecoreExtensions/code/App_Config/Include/Foundation/Foundation.SitecoreExtensions.Serialization.config, src/Foundation/SitecoreExtensions/code/App_Config/Include/Foundation/Foundation.SitecoreExtensions.config, src/Foundation/SitecoreExtensions/code/FieldEditor/FieldEditorAll.cs, src/Foundation/SitecoreExtensions/code/Sitecore.Foundation.SitecoreExtensions.csproj, src/Foundation/SitecoreExtensions/serialization/Foundation.SitecoreExtensions.WebEdit.FieldEditorAll/Default Rendering Buttons.yml, src/Foundation/SitecoreExtensions/serialization/Foundation.SitecoreExtensions.WebEdit.FieldEditorAll/Default Rendering Buttons/Change Position.yml, src/Foundation/SitecoreExtensions/serialization/Foundation.SitecoreExtensions.WebEdit.FieldEditorAll/Default Rendering Buttons/Delete.yml, src/Foundation/SitecoreExtensions/serialization/Foundation.SitecoreExtensions.WebEdit.FieldEditorAll/Default Rendering Buttons/Edit Item.yml, src/Foundation/SitecoreExtensions/serialization/Foundation.SitecoreExtensions.WebEdit.FieldEditorAll/Default Rendering Buttons/Edit related item.yml, src/Foundation/SitecoreExtensions/serialization/Foundation.SitecoreExtensions.WebEdit.FieldEditorAll/Default Rendering Buttons/Edit variations.yml, src/Foundation/SitecoreExtensions/serialization/Foundation.SitecoreExtensions.WebEdit.FieldEditorAll/Default Rendering Buttons/Morph.yml, src/Foundation/SitecoreExtensions/serialization/Foundation.SitecoreExtensions.WebEdit.FieldEditorAll/Default Rendering Buttons/Options.yml, src/Foundation/SitecoreExtensions/serialization/Foundation.SitecoreExtensions.WebEdit.FieldEditorAll/Default Rendering Buttons/Personalize.yml, src/Foundation/SitecoreExtensions/serialization/Foundation.SitecoreExtensions.WebEdit.FieldEditorAll/Default Rendering Buttons/Properties.yml, src/Foundation/SitecoreExtensions/serialization/Foundation.SitecoreExtensions.WebEdit.FieldEditorAll/Default Rendering Buttons/Set datasource.yml
- Added FieldEditorAll class
- Changed Foundation.SitecoreExtensions.Serialization.config
- Changed Foundation.SitecoreExtensions.config
- Added new .yml files for the Core database.
=> Added custom 'Field Editor All' button to the Sitecore Extensions Project

gulpfile-ci.js, scripts/unicorn.js
Previously CI task only was able to enumerate through files.
Added tasks for enumerating items users and roles, so CI-Do-Magic will build complete package.xml
=> Add steps to CI task that go through items and add them to package project

scripts/unicorn.js
=>  #166 cwd not being used when sync unicorn with gulp

src/Feature/Accounts/Tests/ContactProfileServiceTests.cs, src/Feature/Accounts/code/Services/ContactProfileService.cs
Description of the change:
1) Check if tag value exists before calling Sitecore.Analytics.Tracking.IContactTagsContext.Set (Which is more an Add than a Set)
2) Add Unit Tests
=> Bug 38386 Fix -> Interests value duplicates in Mongo DB

src/Project/Habitat/serialization/Habitat.Website.Content/4b86cb93-0ae5-4845-877b-6a045eac5707/Dependencies 1.yml, src/Project/Habitat/serialization/Habitat.Website.Content/4b86cb93-0ae5-4845-877b-6a045eac5707/Dependencies 2.yml, src/Project/Habitat/serialization/Habitat.Website.Content/4b86cb93-0ae5-4845-877b-6a045eac5707/Dependencies 3.yml, src/Project/Habitat/serialization/Habitat.Website.Content/4b86cb93-0ae5-4845-877b-6a045eac5707/Dependencies 4.yml, src/Project/Habitat/serialization/Habitat.Website.Content/4b86cb93-0ae5-4845-877b-6a045eac5707/Dependencies 5.yml, src/Project/Habitat/serialization/Habitat.Website.Content/4b86cb93-0ae5-4845-877b-6a045eac5707/Dependencies 6.yml, src/Project/Habitat/serialization/Habitat.Website.Content/Habitat/Global/Media/DependenciesFolder.yml
Minor change. Just shouldn't have items of the same name in the same directory.
=> Renamed item, avoiding having same-names in the one directory

src/Feature/News/code/Indexing/NewsIndexingProvider.cs, src/Feature/News/code/Repositories/NewsRepository.cs, src/Project/Common/code/App_Config/Include/Project/Common.Website.Serialization.config, src/Project/Common/serialization/Common.Website.BucketSettings/Item Buckets Settings.yml
When a news item was set to publish in the future, there was an error on the news listing page.  I added error handling.  I also changed the bucketing of all news folders to Year / Month to shorten the URLS by changing the Item Bucket Settings item.
=> News enhancements

src/Feature/News/serialization/Feature.News.Templates/News/_NewsArticle/News/NewsBody.yml, src/Feature/News/serialization/Feature.News.Templates/News/_NewsArticle/News/NewsSummary.yml, src/Feature/News/serialization/Feature.News.Templates/News/_NewsArticle/News/NewsTitle.yml
I changed the field validation for title, summary, and body on the news item template.
=> The title, summary, and body of news articles should be required.

src/Feature/News/serialization/Feature.News.Templates/News/_NewsArticle/News/NewsBody.yml, src/Feature/News/serialization/Feature.News.Templates/News/_NewsArticle/News/NewsSummary.yml, src/Feature/News/serialization/Feature.News.Templates/News/_NewsArticle/News/NewsTitle.yml, src/Project/Habitat/serialization/Habitat.Website.Content/Habitat/Global/Links/Footer Menu/Right/Best Practice Blogs.yml
Renamed Best Practise Blogs to Best Practice Blogs
=> Renamed best practise blogs to practice

src/Foundation/Indexing/code/App_Config/Include/Foundation/Foundation.Indexing.config
https://nimbus.everhelper.me/client/notes/share/593459/n0gndofcropi7yhwwzn9
=> Fixed config setting for default ISearchResultFormatter.

scripts/unicorn.js
@yassinealahyane @scottmulligan
=> Trailing slash in publishsettings.targets fixed

src/Foundation/SitecoreExtensions/code/Services/FieldRendererService.cs
=> Makes FieldRendererService thread safe

src/Feature/Demo/code/Repositories/PersonalInfoRepository.cs, src/Feature/Demo/code/Scripts/Demo/VisitDetails.js, src/Feature/Demo/code/Views/Demo/ExperienceData.cshtml
Added tags to Personal Info in the xDB panel
End Visit no longer reloads the page, thereby starting a new visit
=> xDB Panel update

src/Foundation/Assets/code/Sitecore.Foundation.Assets.csproj, src/Foundation/Indexing/code/Sitecore.Foundation.Indexing.csproj, src/Foundation/SitecoreExtensions/code/Sitecore.Foundation.SitecoreExtensions.csproj
Minor fix, that prevents the website folder from containing built files /bin/Debug/.
=> Fixed web projects outputting to bin\[Configuration]

Habitat.sln, src/Foundation/DependencyInjection/code/App_Config/Include/Foundation/Foundation.DependencyInjection.config, src/Foundation/DependencyInjection/code/Infrastructure/MvcControllerServicesConfigurator.cs, src/Foundation/DependencyInjection/code/Lifetime.cs, src/Foundation/DependencyInjection/code/Properties/AssemblyInfo.cs, src/Foundation/DependencyInjection/code/Properties/PublishProfiles/Local.pubxml, src/Foundation/DependencyInjection/code/ServiceCollectionExtensions.cs, src/Foundation/DependencyInjection/code/Sitecore.Foundation.DependencyInjection.csproj, src/Foundation/DependencyInjection/code/Web.Debug.config, src/Foundation/DependencyInjection/code/Web.Release.config, src/Foundation/DependencyInjection/code/Web.config, src/Foundation/DependencyInjection/code/packages.config, src/Foundation/Multisite/code/App_Config/Include/Foundation/Foundation.Multisite.config, src/Foundation/Multisite/code/Placeholders/SiteSpecificPlaceholderCache.cs, src/Foundation/Multisite/code/Placeholders/SiteSpecificPlaceholderCacheManager.cs, src/Foundation/Multisite/code/ServicesConfigurator.cs, src/Foundation/Multisite/code/packages.config, src/Project/Habitat/code/App_Config/Include/Project/Habitat.Website.config
Support for site specific placeholders settings.
Foundation Dependency Injection module.
=> Multisite placeholders

src/Feature/Search/code/Factories/SearchResultsViewModelFactory.cs, src/Feature/Search/code/Models/SearchResultsViewModel.cs, src/Feature/Search/code/Services/SearchService.cs, src/Feature/Search/code/Views/Search/PagedSearchResults.cshtml, src/Foundation/Indexing/code/Infrastructure/Fields/HasSearchResultFormatterComputedField.cs, src/Foundation/Indexing/code/Infrastructure/Fields/SearchResultFormatterComputedField.cs, src/Foundation/Indexing/code/Infrastructure/Providers/FallbackIndexingProvider.cs, src/Foundation/Indexing/code/Services/SearchService.cs, src/Foundation/Indexing/code/Sitecore.Foundation.Indexing.csproj, src/Project/Habitat/serialization/Habitat.Website.Content/Habitat/Global/Dictionary/Search/Header/Title With Results.yml, src/Project/Habitat/serialization/Habitat.Website.Content/Habitat/Home.yml
Null errors
Removed unwanted search results
Fixed page index vs page number
=> Search review fixes

src/Feature/Search/code/Models/PagingSettings.cs, src/Feature/Search/code/Views/Search/SearchFacets.cshtml, src/Feature/Search/serialization/Feature.Search.Renderings/Search/Search Facets.yml, src/Feature/Search/serialization/Feature.Search.Renderings/Search/Search Results Header.yml
For some reason the files were missing in the last PR
=> Search bugs

CONTRIBUTING.md
Pedantic markdown fix so headings display correctly.
=> Fix heading markup

src/Feature/Demo/code/Controllers/DemoController.cs
* issue originated in previous refactoring of ExperienceData
=> [#417] Fix for Null Model in Demo Controller

README.md, docs/01-Getting-Started.md
* [#419] added instructions on Facebook Login configuration
* [#421] added instructions to rebuild search indexes when setting up Habitat
* [#425] added clearer language to README regarding support
=> Documentation Updates

docs/01-Getting-Started.md, gulpfile.js, src/Feature/Accounts/Tests/app.config, src/Feature/Demo/tests/app.config, src/Feature/Language/Tests/app.config, src/Feature/Maps/tests/app.config, src/Feature/Media/Tests/app.config, src/Feature/Multisite/tests/App.config, src/Feature/News/Tests/app.config, src/Feature/Person/tests/app.config, src/Feature/Teasers/tests/App.config, src/Foundation/Accounts/tests/app.config, src/Foundation/Alerts/tests/app.config, src/Foundation/Dictionary/tests/app.config, src/Foundation/FieldEditor/tests/app.config, src/Foundation/Indexing/Tests/app.config, src/Foundation/Installer/tests/app.config, src/Foundation/LocalDatasource/tests/App.config, src/Foundation/Multisite/tests/App.config, src/Foundation/SitecoreExtensions/Tests/app.config, src/Foundation/Testing/tests/app.config, src/Foundation/Theming/tests/App.config
* Some Getting Started doc fixes
* Removed copying of Sitecore libs -- all nuget now
* Removed copying of Sitecore license -- already placed in build/assets
=> [#427] Getting Started Updates

build/Certificates/solr-ssl.ps1, build/GenerateSolrCertificate.ps1
Includes #444 and one additional keystore check
=> Brunomartinspro master

docs/index.md
=> Fix link to docs

docs/02-Resources.md
=> [#440] document VS17 15.5 requirement
